name: Build and test solution projects

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore "source/FlightScanner.sln"
      
    - name: Build
      run: dotnet build --no-restore "source/FlightScanner.sln"

    - name: Run dotnet format
      run: dotnet format "source/FlightScanner.sln" --no-restore --verify-no-changes --exclude source/FlightScanner.Client.BlazorWA/Program.cs
      
    - name: Test
      run: dotnet test --no-build --verbosity normal "source/FlightScanner.sln"   